# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-15 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='owndevice',
            name='memo',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='owndevice',
            name='owndevice',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='主机'),
        ),
    ]
