# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-27 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190315_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='disk',
            name='iface_type',
            field=models.CharField(choices=[('SATA', 'SATA'), ('SAS', 'SAS'), ('SCSI', 'SCSI'), ('SSD', 'SSD'), ('virtual', 'virtual')], default='SATA', max_length=64, verbose_name='接口类型'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='slot',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='插槽位'),
        ),
    ]
