# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-01-13 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20190627_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='capacity',
            field=models.CharField(max_length=32, verbose_name='内存大小（MB）'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='slot',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='插槽'),
        ),
    ]
