# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-12 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20200311_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nic',
            old_name='boding',
            new_name='bonding',
        ),
    ]
