# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-12 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20200312_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nic',
            old_name='macadderss',
            new_name='macaddress',
        ),
    ]
