# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-12 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20200312_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='model',
            field=models.CharField(max_length=16, verbose_name='网卡类型'),
        ),
    ]
