# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20200312_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='应用系统名称')),
                ('enName', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文简称')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='状态')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='组织部门')),
                ('secuityLev', models.IntegerField(blank=True, null=True, verbose_name='等保等级')),
                ('businessTy', models.CharField(blank=True, max_length=50, null=True, verbose_name='业务类型')),
                ('releasePipeline', models.CharField(blank=True, max_length=50, null=True, verbose_name='发布流水线')),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '应用系统',
                'verbose_name': '应用系统',
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='中心名称')),
                ('enName', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文简称')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '中心',
                'verbose_name': '中心',
            },
        ),
        migrations.CreateModel(
            name='ChildSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='子系统名称')),
                ('enName', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文名称')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('state', models.CharField(blank=True, choices=[(0, '已上线'), (1, '已下线'), (2, '故障'), (3, '维修中')], default=0, max_length=50, verbose_name='状态')),
                ('businessLevel', models.CharField(blank=True, max_length=50, null=True, verbose_name='业务级别')),
                ('applicationPort', models.IntegerField(blank=True, null=True, verbose_name='端口')),
                ('secondSupportTeam', models.CharField(blank=True, max_length=50, null=True, verbose_name='二线支持团队')),
                ('ownerMainName', models.CharField(blank=True, max_length=50, null=True, verbose_name='所有者')),
                ('ownerPrePareName', models.CharField(blank=True, max_length=50, null=True, verbose_name='所有者备')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '子系统',
                'verbose_name': '子系统',
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='集群名称')),
                ('env', models.CharField(blank=True, max_length=200, null=True, verbose_name='集群环境')),
                ('architecture', models.CharField(blank=True, max_length=50, null=True, verbose_name='模块架构')),
                ('deploymentType', models.CharField(blank=True, max_length=50, null=True, verbose_name='模块类型')),
                ('state', models.CharField(blank=True, choices=[(0, '运行中'), (1, '已下线'), (2, '集群异常'), (3, '维护中')], default=0, max_length=50, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '集群信息',
                'verbose_name': '集群信息',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='环境名称')),
                ('enName', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文名称')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '环境',
                'verbose_name': '环境',
            },
        ),
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='模块名称')),
                ('env', models.CharField(blank=True, max_length=50, null=True, verbose_name='所处环境')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='物理机名称')),
                ('serviceIp', models.CharField(blank=True, max_length=64, null=True, verbose_name='服务ip')),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='manufactory',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='owndevice',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='businessunit',
            name='parent_unit',
        ),
        migrations.AlterUniqueTogether(
            name='cabinet',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='disk',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='disk',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='fireware',
        ),
        migrations.RemoveField(
            model_name='newassetapprovalzone',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='raidadaptor',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='raidadaptor',
            name='asset',
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ram',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='reqlog',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='safetydevice',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='software',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='server',
            options={},
        ),
        migrations.RemoveField(
            model_name='server',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='server',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='server',
            name='model',
        ),
        migrations.RemoveField(
            model_name='server',
            name='os_distribution',
        ),
        migrations.RemoveField(
            model_name='server',
            name='os_release',
        ),
        migrations.RemoveField(
            model_name='server',
            name='os_type',
        ),
        migrations.RemoveField(
            model_name='server',
            name='raid_type',
        ),
        migrations.RemoveField(
            model_name='server',
            name='sub_asset_type',
        ),
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='物理机名称'),
        ),
        migrations.AddField(
            model_name='server',
            name='serviceIp',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='服务ip'),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
        migrations.DeleteModel(
            name='Cabinet',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='CPU',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
        migrations.DeleteModel(
            name='IDC',
        ),
        migrations.DeleteModel(
            name='Manufactory',
        ),
        migrations.DeleteModel(
            name='NetworkDevice',
        ),
        migrations.DeleteModel(
            name='NewAssetApprovalZone',
        ),
        migrations.DeleteModel(
            name='NIC',
        ),
        migrations.DeleteModel(
            name='Owndevice',
        ),
        migrations.DeleteModel(
            name='RaidAdaptor',
        ),
        migrations.DeleteModel(
            name='RAM',
        ),
        migrations.DeleteModel(
            name='ReqLog',
        ),
        migrations.DeleteModel(
            name='SafetyDevice',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserAdmin',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='system',
            name='server',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Server', verbose_name='所属物理机'),
        ),
        migrations.AddField(
            model_name='appsystem',
            name='supportteam',
            field=models.ManyToManyField(blank=True, to='asset.SupportTeam', verbose_name='执行信息'),
        ),
        migrations.AddField(
            model_name='appsystem',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.System', verbose_name='所属系统'),
        ),
    ]
