# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-23 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdeployhostmess',
            name='remote_port',
            field=models.IntegerField(blank=True, max_length=64, verbose_name='远程登录端口'),
        ),
    ]
