# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-23 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt_restapi', '0002_auto_20200423_1127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentdeployhostmess',
            unique_together=set([('id', 'hostip')]),
        ),
    ]
