# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-04-23 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt_restapi', '0004_auto_20200423_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdeployhostmess',
            name='hostip',
            field=models.CharField(blank=True, max_length=64, verbose_name='主机ip'),
        ),
        migrations.AlterUniqueTogether(
            name='agentdeployhostmess',
            unique_together=set([('id', 'hostip')]),
        ),
    ]
